### ISSUE TITLE
尝试安装了插件 但是(随机打开了三个视频)都没有在页面上出现插件按钮

### ISSUE THREAD

**Issue by th3weird0** [1c7/Youtube-Auto-Subtitle-Download#14]
[UserAgent]
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36

[什么情况]
我是给你发gmail的那个睿智hhh，当时想搬运一个视频嘛，因为想在b站找一个特定的[视频](https://www.youtube.com/watch?v=bInJjmH31Hk)给小伙伴看，但是搜了一遍搬运并没有看到，但又不打算直接扒了视频就投稿，还是打算自己弄一份字幕的……

题外话了，打开您的github仓库看到有一版 Youtube-Auto-Subtitle-Download的插件。
点了安装之后有尝试过：关闭chrome（包括杀掉进程树），在tampermonkey里面删除插件重新装插件，没有改善，在播放页还是加载不出插件提供的窗口
![$GAKT@C@TM$O0KX3K_S1376](https://user-images.githubusercontent.com/68617067/126914404-6d95a883-5b7a-499e-afb6-b575543a2b71.png)
但是我的机器装了IDM，IDM自动抓取了一个.vtt的字幕链接：
![32KR%J%%HMKA1Q~TRP9SKTL](https://user-images.githubusercontent.com/68617067/126914536-60799e4d-09b6-405b-be57-1fe8328cafd3.png)
我可以下载，也可以本地打开，链接是[这个](https://www.youtube.com/api/timedtext?v=bInJjmH31Hk&asr_langs=de%2Cen%2Ces%2Cfr%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru&caps=asr&exp=xftt&xorp=true&xoaf=5&hl=zh-CN&ip=0.0.0.0&ipbits=0&expire=1627274197&sparams=ip%2Cipbits%2Cexpire%2Cv%2Casr_langs%2Ccaps%2Cexp%2Cxorp%2Cxoaf&signature=61F925A24395268916B20C4ADB44779A83358177.21A224D6905CA738E2FB60645B51CA976CC5E3C5&key=yt8&kind=asr&lang=en&fmt=vtt&xorb=2&xobt=3&xovt=3)，但导入premiere之后发现每一行都会有一句话重叠。
![image](https://user-images.githubusercontent.com/68617067/126914548-5debc932-b6cd-458b-8bc3-7cfd4cff89b1.png)
![BX7@G{71Z~1C`I$Z}6XFBDR](https://user-images.githubusercontent.com/68617067/126914576-f6452116-e0c9-49f5-874a-337b57522b64.png)

之前有尝试过安装您的那个双语字幕的插件，那个可以安装也可以使用。

然后现在问题就是插件可以安装的上去，但是u2b播放页无法显示插件窗口……

[联系方式]
我可以辅助重现情况，加你qq，teamviewer，向日葵，Issue树之后的讨论，都可以的。如果您可以帮助我看一下什么情况的话那就太感谢不过了。

**Comment by 1c7** [comment]
内容有点长…我先吃完早餐再来看看

**Comment by th3weird0** [comment]
早上好dalao 我给你issue了 在GitHub上

**Comment by 1c7** [comment]
https://www.youtube.com/watch?v=bInJjmH31Hk

![image](https://user-images.githubusercontent.com/1804755/126926439-b5a2102e-2a07-4949-80cc-eca6bcf430a6.png)
[(英语 (自动生成))Sony WH-1000XM4 Review_ The Final Form!_video_id_bInJjmH31Hk.srt.zip]

(https://github.com/1c7/Youtube-Auto-Subtitle-Download/files/6875232/Sony.WH-1000XM4.Review_.The.Final.Form._video_id_bInJjmH31Hk.srt.zip)

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/126926529-931ba53a-5446-4501-a838-f13e82975544.png)

**Comment by 1c7** [comment]
无法复现问题，显示和下载均正常

**Comment by 1c7** [comment]
一般有这样的问题，刷新页面即可，让 tampermonkey 刷新后能正确载入插件。
因为  Youtube 本身的跳转页面不是常规的跳转，所以点击一个视频，进入播放页，这个过程中插件没法正确加载

**Comment by th3weird0** [comment]
好的 虽然我刷新了很多很多次之后也没好 要不先这样？

**Comment by 1c7** [comment]
OK。

说点题外话，
我是 macOS + Chrome 92。

不能用可能是这几类问题：
1. Youtube 改接口改代码了（但是我能用，从而可以得知不是这个问题）
2. 环境问题
3. 网络问题
4. 权限问题

### 环境问题： 
比如插件冲突了，我建议关闭 Tampermonkey 之外的其他所有 Chrome 插件。   
关闭 Tampermonkey 里所有其他脚本。

### 网络问题
就是翻墙呗，我是全局翻墙的。
这个脚本里面我记得依赖了 jQuery，那个 jQuery 的 CDN 可能因为某些原因没能正常访问。

### 权限问题
装了脚本之后的权限弹窗没有给允许。

**Comment by th3weird0** [comment]
谢谢您细心解答 我开个vm 在vm里面再试一下

**Comment by th3weird0** [comment]
问题解决了！

在梯子开了GLOBAL之后我去看梯子log 有显示code.jquery.com走的是proxy 但我去访问code.jquery.com一直TIME_OUT

然后我在怀疑是不是节点的问题。因为毕竟之前没有弹过权限窗口。

截至此时用的是某个日本GMO线路的小梯，换了台湾HiNet之后就可以加载需要的jQuery了
![image](https://user-images.githubusercontent.com/68617067/126936750-3b41f605-6f5a-419e-904b-7fb1e2075343.png)

**如果有朋友也遇到我这种问题，请试着切换节点。**

另外，作者大大有办法把[这个指定资源](https://code.jquery.com/jquery-1.12.4.min.js)“封装”到js内吗 就是用户安装的时候点添加到Tampermonkey即可添加JavaScript脚本+脚本所需要的jQuery（只是一个不成熟的想法）

**Comment by th3weird0** [comment]
另外谢谢作者的指导 CDN这个问题确实很难想到

**Comment by 1c7** [comment]
ok, 问题解决了就行, 我继续上班
