### ISSUE TITLE
相似项目交流一下（同时观看多字幕的扩展）

### ISSUE THREAD

**Issue by garywill** [1c7/Youtube-Auto-Subtitle-Download#15]
我最近弄的一个[在youtube网页观看时同时显示多语言字幕的扩展](https://github.com/garywill/multi-subs-yt)（已上架Firefox，也可以port到Chrome）

@1c7 非常感谢您的这个下载字幕的项目，期间有给过我一些启发

一点建议：
我看见你使用`window.ytplayer.config`来获取信息
而后来我发现从`<ytd-app>`这个HTML tag里获取信息似乎是更好的方案
```js
document.getElementsByTagName("ytd-app")[0].data.playerResponse
```
不像`window.ytplayer.config`一样经过导航后信息失效，
这个`<ytd-app>`是会实时更新的，这样切换视频后的新信息不必要再从`yt-navigate-finish`的event中取

**Comment by 1c7** [comment]
v30 -> v31  
v11 -> v12  
v10 -> v11  

给3个脚本都升级了，都是用了
```javascript
document.getElementsByTagName("ytd-app")[0].data.playerResponse
```

好用。 感谢

**Comment by 1c7** [comment]
我先关掉这个 issue，毕竟放了一年多了。~ 有事情再聊~
