### ISSUE TITLE
How do I change the color of the frame?

### ISSUE THREAD

**Issue by Kuju29** [1c7/Youtube-Auto-Subtitle-Download#16]
I'd want to have the color match the background. Thanks!
![image](https://user-images.githubusercontent.com/22098092/147378973-8f5d6170-5cb3-4233-9a38-819282055ab1.png)

**Comment by 1c7** [comment]
Probably this line: https://github.com/1c7/Youtube-Auto-Subtitle-Download/blob/e8e81b73341b8310d5785c3a6e7d9858f0a4a92e/Youtube-Subtitle-Downloader/Tampermonkey.js

**Comment by Kuju29** [comment]
> Probably this line:
> 
> https://github.com/1c7/Youtube-Auto-Subtitle-Download/blob/e8e81b73341b8310d5785c3a6e7d9858f0a4a92e/Youtube-Subtitle-Downloader/Tampermonkey.js#L201

it work. Thank <3 ^_^
