### ISSUE TITLE
Smartphone adapting

### ISSUE THREAD

**Issue by michael1900** [1c7/Youtube-Auto-Subtitle-Download#18]
Hi. How to adapt this for a smartphone screen? For the buttons for example.

**Comment by 1c7** [comment]
Probably wouldn't work on phone(Chrome/Firefox/Safari), 
Because on the Desktop Browser, it rely on Tampermonkey to load this Javascript script.
I don't think on mobile there are things similiar to Tampermonkey to load Javascript script.

**Comment by AntonOfTheWoods** [comment]
You might be able to use the Kiwi browser on Android. I make a quite complicated chrome extension that currently works fine on Kiwi. At times the Yandex browser also works with most extensions but not at the moment.

It absolutely 100% can never work on iOS though, so if that is a requirement then forget about it.

**Comment by 1c7** [comment]
@AntonOfTheWoods Thanks for the information.
I only have an iPhone right now, I don't have any Android phone.
Can't help @michael1900

**Comment by AntonOfTheWoods** [comment]
Thanks @1c7 . I started to have a look but I couldn't get anything to work. On a Linux desktop Edge gives a button but when I click on any of the options nothing happens. In Chrome absolutely no button appears at all.

**Comment by 1c7** [comment]
@AntonOfTheWoods
I did not understand what you mean.  

`Youtube Subtitle Downloader v32` and few other script I wroted (complete list check here: https://greasyfork.org/zh-CN/users/5711-1c7)
Should work fine on macOS + Chrome (My development and testing environment)

You mean on Linux Desktop both Edge&Chrome can't get `Youtube Subtitle Downloader v32` to work properly?

**Comment by AntonOfTheWoods** [comment]
@1c7  that is correct. The button doesn't appear at all on Chrome and appears but doesn't do anything on Edge. I don't see any errors in the console, though I'm not sure that errors with GreaseMonkey will show there or not.

**Comment by 1c7** [comment]
@AntonOfTheWoods 
I am not gonna spend time to make my script compatible to as many enviroment as possible.   
If you want the script to work on Linux, 
Since the code is open source, you could try to modify the code to make it work on Linux + Chrome & Edge.

**Comment by 1c7** [comment]
Some of the code comment are in Chinese, but that shouldn't be a big problem.  
All the function name and variable name are in English.
