### ISSUE TITLE
youtube改版后无法找到下载按键

### ISSUE THREAD

**Issue by BingLingGroup** [1c7/Youtube-Auto-Subtitle-Download#19]
youtube好像前段时间改版了，现在在打开插件的状态下无法找到下载的按键

**Comment by 1c7** [comment]
好的，收到，他那个改版好像是灰度，一部分人有一部分人没有。
我这个仓库里有好几个 script，你用的具体是哪一个？我先修大家都在用的一个，其他的可以先放放。

**Comment by BingLingGroup** [comment]
原来是灰度测试啊，我刚才用没登陆的状态才发现，那不着急，说不定过几天又被砍了。
我用的主要是 [Youtube 下载自动字幕的字词级文件](https://github.com/1c7/Youtube-Auto-Subtitle-Download/tree/master/Youtube%20%E4%B8%8B%E8%BD%BD%E8%87%AA%E5%8A%A8%E5%AD%97%E5%B9%95%E7%9A%84%E5%AD%97%E8%AF%8D%E7%BA%A7%E6%96%87%E4%BB%B6) 和 [Youtube-Subtitle-Downloader](https://github.com/1c7/Youtube-Auto-Subtitle-Download/tree/master/Youtube-Subtitle-Downloader) 这两个，你如果有空的话可以改下。

**Comment by 1c7** [comment]
好的。

**Comment by 1c7** [comment]
Youtube-Subtitle-Downloader 从 v32 升级到了 v33 应该是修好了。起码我这边测试是修好了。
https://greasyfork.org/zh-CN/scripts/5368-youtube-subtitle-downloader-v33

**Comment by 1c7** [comment]
Youtube 下载自动字幕 (字词级) v5 也发布了，修好了此问题。
https://greasyfork.org/zh-CN/scripts/422083-youtube-%E4%B8%8B%E8%BD%BD%E8%87%AA%E5%8A%A8%E5%AD%97%E5%B9%95-%E5%AD%97%E8%AF%8D%E7%BA%A7-v5

**Comment by 1c7** [comment]
问题应该是解决了，我先 close，你试验完如果不行那就再聊

**Comment by BingLingGroup** [comment]
好的，谢谢

**Comment by starobots** [comment]
您好，安装v34版本的下载插件，也是没找到绿色的下载按钮。
麻烦您
谢谢！

![image](https://user-images.githubusercontent.com/10796457/193727406-ddc3a40d-7d99-441d-a415-3e60f2b7fe39.png)

**Comment by starobots** [comment]
我有2个还是3个ytb账号是老版本，剩下的账号是新版本。我就试了老版本用这个插件，没找到下载的按钮。
这个插件是适配新版本的吗？

**Comment by 1c7** [comment]
对的，只能新版本。
