### ISSUE TITLE
报告一个bug

### ISSUE THREAD

**Issue by mirage1993** [1c7/Youtube-Auto-Subtitle-Download#2]
本来想看看代码，提交个更改，结果无奈没学过js，根本看不懂~
https://www.youtube.com/watch?v=p2J7wSuFRl8&list=PLEA18FAF1AD9047B0&index=1
这个YouTube链接用complete subtitle download下载字幕，下完后我发现是下面这样：
![default](https://cloud.githubusercontent.com/assets/8112645/5645475/ade95780-96aa-11e4-9c7f-edbe3800d357.JPG)

也就是说前面的序号和正文之间没有回车了。但是在notepad里面显示是有回车的。我估计是编码问题。
另外这时间轴确实是出问题了。都是这样的00:00:01,200 --> 00:00:
不过这东西真是帮了大忙了。多谢开发这个脚本！

**Comment by 1c7** [comment]
@mirage1993   https://greasyfork.org/zh-CN/scripts/5368-youtube-subtitle-downloader   问题已修复，请重新安装谢谢 :D

**Comment by mirage1993** [comment]
@1c7 多谢~
