### ISSUE TITLE
Missing button: "Download subtitles".

### ISSUE THREAD

**Issue by NikSavchenk0** [1c7/Youtube-Auto-Subtitle-Download#21]
I'm not have a button "Download subtitles"...
![image](https://github.com/user-attachments/assets/f6b0e2bc-ecda-429b-8812-4bcc56822019)

**Comment by 1c7** [comment]
Thank you for your feedback, but unfortunately, I am unable to fix this issue at the moment. Please consider this script as no longer maintained. I apologize for any inconvenience this may cause and appreciate your understanding.
