### ISSUE TITLE
自动翻译的字幕无法下载

### ISSUE THREAD

**Issue by flamefox** [1c7/Youtube-Auto-Subtitle-Download#3]
就是自动英文->其他语言的翻译

**Comment by 1c7** [comment]
这不是个 bug，
纯粹就是 "自动英文->其他语言的翻译" 这个功能没做。
因为觉得没有必要，自动英文的正确率本身在 80%~95% 左右。
翻译出来的话意思差远了，可参考的意义不大。

不过如果用来做字幕的话到时可以拿来用来节省时间，可以少打几个字。
毕竟大部分情况，修改一下自动翻译句子里的几个字就行了。
话说你觉得有必要做一个这样的功能吗？
你需要这个功能是拿来做什么呢？
我是不希望花时间去做一个很少很少人用的功能
