### ISSUE TITLE
下载字幕报错

### ISSUE THREAD

**Issue by 772807886** [1c7/Youtube-Auto-Subtitle-Download#5]
Chrome版本：56.0.2891.0 canary (64-bit)
Tampermonkey版本：4.2.5330
出错时机：在列表里选择了语言之后立即出现。
报错信息：
![bug](https://cloud.githubusercontent.com/assets/10294977/19428366/46e00788-947c-11e6-9027-4c58b075aa21.png)

**Comment by 1c7** [comment]
版本 56 的 canary。好新的版本啊。（土豪金图标哈哈哈）
我更新了下我自己的，现在我的版本是 54.0.2840.59 m（我用的普通版）
谢反馈！
