### ISSUE TITLE
Only support the classic Youtube

### ISSUE THREAD

**Issue by Jay54520** [1c7/Youtube-Auto-Subtitle-Download#7]
I find that it doesn't display ` == Get (auto-generated) Subtitle | 下载自动字幕 == ` if your Youtube is not classic version. You should check to the classic Youtube version.
![image](https://user-images.githubusercontent.com/13315364/27738011-ce960cc0-5ddc-11e7-8ddd-5ab534118db7.png)
I think you should add this to `README`.

**Comment by 1c7** [comment]
I will, thanks for advice

**Comment by 1c7** [comment]
updated!
